import Hearders from "@/components/Hearders";
import { getDocuments } from "@/lib/docs";
import localFont from "next/font/local";
import "./globals.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Documentation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const allDocments = getDocuments();
  // console.log(allDocments);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-full lg:ml-72 xl:ml-80">
          <Hearders docs={allDocments} />
          {children}
        </div>
      </body>
    </html>
  );
}
